#server: #디폴트 8080
#  port: 9090
#타임리프 템플릿 엔진 디폴트 설정
spring:
  thymeleaf:
    cache: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html		
#정적자원의 디폴트 설정

  mvc:
    static-path-pattern: /**  #정적자원의 URL 설정
  web:
    resources:
      static-locations: classpath:/static/ #정적자원의 물리적 위치 설정
      add-mappings: true #자동매핑 활성화

#messages.properties파일의 디폴트 설정(디폴트값 messages ).단,i18n폴더를 생성해야 한다
  messages: 
    basename: i18n/messages	
#데이타 베이스 연결을 위한 설정  
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: SPRING
    password: SPRING
#스프링 부트의 디폴트 커넥션 풀인 Hikari 디폴트 설정.
#https://github.com/brettwooldridge/HikariCP?tab=readme-ov-file#frequently-used    
    hikari:
      auto-commit: true
      connection-timeout: 30000
      maximum-pool-size: 10			
#Spring-Data-JPA설정
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #JPA 컬럼명 전략

    properties:
      hibernate:
        format_sql: true #DDL문 가독성 있게 표시	
    show-sql: true  #JPA쿼리 로그 확인용   			
#컨텍스트 루트 디폴트 설정 및 세션 유효시간 디폴트 설정(30분)    
server:
  servlet:
    context-path: /
    session:
      timeout: 1800
#아래 처럼 설정시는 http://localhost:8080/myapp 으로 요청해야한다
#server:
#  servlet:
#    context-path: /myapp

#사용자 정의 키
mykey:
  yourkey:
    wekey: love










